In [1]:
import pandas as pd
import numpy as np
import scipy.stats as st
import os


In [7]:
!wget --no-clobber https://raw.githubusercontent.com/stefannae/SIC-Artificial-Intelligence/main/SIC_AI_Coding_Exercises/SIC_AI_Chapter_04_Coding_Exercises/data_iris.csv

--2024-08-06 11:24:45--  https://raw.githubusercontent.com/stefannae/SIC-Artificial-Intelligence/main/SIC_AI_Coding_Exercises/SIC_AI_Chapter_04_Coding_Exercises/data_iris.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 2606:50c0:8000::154, 2606:50c0:8003::154, 2606:50c0:8001::154, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|2606:50c0:8000::154|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3867 (3.8K) [text/plain]
Saving to: ‘data_iris.csv’

data_iris.csv       100%[===================>]   3.78K  --.-KB/s    in 0s      

2024-08-06 11:24:46 (78.6 MB/s) - ‘data_iris.csv’ saved [3867/3867]



In [9]:
# Read in the data.
df = pd.read_csv('data_iris.csv', header='infer')

In [11]:
 df.shape

(150, 5)

In [13]:
df.head(3)

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa

In [15]:
 # Set aside two variables.
x = df['Petal.Length']
y = df['Sepal.Length']


In [17]:
 # Using the SciPy function.
# Correlation and p-value.
np.round(st.pearsonr(x,y),3)


array([0.872, 0.   ])

In [19]:
# Using the Pandas function.
x.corr(y)

0.8717537758865832

In [27]:
 # Correlation array.
# np.round(df.corr(),3)


In [23]:
 # Using the SciPy function.
# Correlation and p-value.
np.round(st.spearmanr(x,y),3)


array([0.882, 0.   ])

In [29]:
 # Using the SciPy function.
# Correlation and p-value.
np.round(st.kendalltau(x,y),3)

array([0.719, 0.   ])

In [31]:
!wget --no-clobber https://raw.githubusercontent.com/stefannae/SIC-Artificial-Intelligence/main/SIC_AI_Coding_Exercises/SIC_AI_Chapter_04_Coding_Exercises/data_studentlist.csv

--2024-08-06 11:27:39--  https://raw.githubusercontent.com/stefannae/SIC-Artificial-Intelligence/main/SIC_AI_Coding_Exercises/SIC_AI_Chapter_04_Coding_Exercises/data_studentlist.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 2606:50c0:8001::154, 2606:50c0:8003::154, 2606:50c0:8000::154, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|2606:50c0:8001::154|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 674 [text/plain]
Saving to: ‘data_studentlist.csv’

data_studentlist.cs 100%[===================>]     674  --.-KB/s    in 0s      

2024-08-06 11:27:40 (60.5 MB/s) - ‘data_studentlist.csv’ saved [674/674]



In [33]:
# Read in another data set.
df = pd.read_csv('data_studentlist.csv', header='infer')


In [35]:
df.head(3)


name gender  age  grade absence bloodtype  height  weight
0   Jared Diamond      M   23      3       Y         O   165.3    68.2
1  Sarah O'Donnel      F   22      2       N        AB   170.1    53.0
2    Brian Martin      M   24      4       N         B   175.0    80.1

In [37]:
 # Set aside two variables.
x = df.height
y = df.weight


In [39]:
# Apply the Fisher's z-transformation.
# See the lecture.
n = len(x)
r = x.corr(y)
z = np.arctanh(r)
std_error_z = 1/np.sqrt(n-3)

In [43]:
# 95% confidence interval.
# Expressed as a dictionary object.
{'low':np.tanh(z-st.norm.ppf(0.975)*std_error_z), 'high': np.tanh(z+st.norm.ppf(0.975)*std_error_z)}

{'low': 0.26960396330592235, 'high': 0.8677953581441814}

In [45]:
 # 99% confidence interval.
# Expressed as a dictionary object.
{'low':np.tanh(z-st.norm.ppf(0.995)*std_error_z), 'high': np.tanh(z+st.norm.ppf(0.995)*std_error_z)}


{'low': 0.11137578298592958, 'high': 0.9030812794020874}